### ISSUE TITLE
The accuracy of the model in this paper

### ISSUE THREAD

**Issue by DuanhaoranCC** [flyingtango/DiGCL#1]
Hello, your work is very valuable. I'd like to ask you:
Compare your paper with other methods, why the performance of other methods is low (different from the original paper, what is the reason?). Is it the result of training 20 labels for each class in each data set and testing and evaluation 10 times?
Thank you very much for your answer!

**Comment by flyingtango** [comment]
Hi,

Thank you for your interest in our work. 
There are two reasons, first for the directed graph dataset is due to the direction of the edges, and the other reason is what you mentioned, we use a very low labeling rate, only 20 samples per class, while for example GCA, they use a labeling rate of 10%. We use the labeling rate from Kipf's paper, and for semi-supervised node classification, a decrease in labeling rate leads to a decrease in accuracy.

Regards,
Zekun

**Comment by DuanhaoranCC** [comment]
Well, thank you for your answer. The last question is how to input three directed data sets into undirected graph models such as GCN, GAT, GRACE, etc.

**Comment by flyingtango** [comment]
Hi,

The input is straightforward that just need to make sure the inputed adjacency matrix is directed (asymmetric). You can refer to the input in this [repo](https://github.com/flyingtango/DiGCN).

Regards,
Zekun
